DELETE FROM ResourceGroup;
DELETE FROM PrivacySetting;
DELETE FROM App;
DELETE FROM ServiceFeature;
DELETE FROM Preset;
DELETE FROM ServiceFeature_RequiredPrivacySettingValue;
DELETE FROM Preset_GrantedPrivacySettingValue;
DELETE FROM Preset_AssignedApp;
DELETE FROM Context_AnnotatedPrivacySettingValue;